it('should add a upvote to a post/comment successfuly', () => {});
it('should add a downvote to a post/comment successfuly', () => {});
it('should throw when no postId or commentId are provided', () => {});
it('should throw when both postId and commentId are provided', () => {});
it('should throw when post/comment is not found', () => {});
it('should throw when post/comment is already upvoted', () => {});
it('should throw when post/comment is already downvoted', () => {});
it('should update a upvote to downvote on a post/comment successfuly', () => {});
it('should update a downvote to upvote on a post/comment successfuly', () => {});
